# -*- coding: utf-8 -*-
"""Tetrio_stuff

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OMBxp7ni5MvFnMggYvkWiZsE_nXECfgX
"""

import math
from collections import deque
import numpy as np
from typing import Optional

try:
    from numba import njit
    NUMBA_AVAILABLE = True
except ImportError:
    def njit(*args, **kwargs):
        def decorator(func):
            return func
        return decorator if not args else decorator(args[0])
    NUMBA_AVAILABLE = False

BOARD_WIDTH = 10
BOARD_HEIGHT = 40
VISIBLE_HEIGHT = 20
HIDDEN_ROWS = BOARD_HEIGHT - VISIBLE_HEIGHT
SPAWN_X = 3
SPAWN_Y = max(0, HIDDEN_ROWS - 2)

PIECE_ID_TO_KIND = {
    1: "I", 2: "O", 3: "T", 4: "S", 5: "Z", 6: "J", 7: "L",
}
KIND_TO_PIECE_ID = {v: k for k, v in PIECE_ID_TO_KIND.items()}

PIECE_DEFS = {
    "I": {"size": 4, "blocks": [(0, 1), (1, 1), (2, 1), (3, 1)]},

    "O": {"size": 4, "blocks": [(1, 1), (2, 1), (1, 2), (2, 2)]},

    "T": {"size": 3, "blocks": [(1, 0), (0, 1), (1, 1), (2, 1)]},

    "S": {"size": 3, "blocks": [(1, 0), (2, 0), (0, 1), (1, 1)]},

    "Z": {"size": 3, "blocks": [(0, 0), (1, 0), (1, 1), (2, 1)]},

    "J": {"size": 3, "blocks": [(2, 0), (0, 1), (1, 1), (2, 1)]},

    "L": {"size": 3, "blocks": [(0, 0), (0, 1), (1, 1), (2, 1)]},
}

JLSTZ_OFFSETS = {
    0: [(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)],
    1: [(0, 0), (1, 0), (1, -1), (0, 2), (1, 2)],
    2: [(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)],
    3: [(0, 0), (-1, 0), (-1, -1), (0, 2), (-1, 2)],
}

I_OFFSETS = {
    0: [(0, 0), (-1, 0), (2, 0), (-1, 0), (2, 0)],
    1: [(-1, 0), (0, 0), (0, 0), (0, 1), (0, -2)],
    2: [(-1, 1), (1, 1), (-2, 1), (1, 0), (-2, 0)],
    3: [(1, 0), (0, 0), (0, 0), (0, 1), (0, -2)],
}

O_OFFSETS = {
    0: [(0, 0)], 1: [(0, 0)], 2: [(0, 0)], 3: [(0, 0)]
}

KICKS_180_NS = [
    (0, 0), (0, 1), (1, 1), (-1, 1), (0, -1)
]
KICKS_180_EW = [
    (0, 0), (1, 0), (1, 2), (1, 1), (0, 2)
]

JLSTZ_OFFSETS_ARR = np.array(
    [JLSTZ_OFFSETS[0], JLSTZ_OFFSETS[1], JLSTZ_OFFSETS[2], JLSTZ_OFFSETS[3]],
    dtype=np.int8,
)
I_OFFSETS_ARR = np.array(
    [I_OFFSETS[0], I_OFFSETS[1], I_OFFSETS[2], I_OFFSETS[3]],
    dtype=np.int8,
)
O_OFFSETS_ARR = np.array(
    [O_OFFSETS[0], O_OFFSETS[1], O_OFFSETS[2], O_OFFSETS[3]],
    dtype=np.int8,
)
KICKS_180_NS_ARR = np.array(KICKS_180_NS, dtype=np.int8)
KICKS_180_EW_ARR = np.array(KICKS_180_EW, dtype=np.int8)


def _rotate_coords(coords, size, direction):
    """
    Rotates coordinates around the center.
    System: Y-Axis is DOWN.
    Direction: 1 = CW, -1 = CCW, 2 = 180
    """
    center = (size - 1) / 2.0
    rotated = []
    for x, y in coords:
        dx = x - center
        dy = y - center

        # Matrix Rotation for Y-Down System
        if direction == 1:       # CW: x' = -y, y' = x
            rx, ry = -dy, dx
        elif direction == -1:    # CCW: x' = y, y' = -x
            rx, ry = dy, -dx
        elif direction in (2, -2): # 180: x' = -x, y' = -y
            rx, ry = -dx, -dy
        else:
            raise ValueError(f"Invalid dir: {direction}")

        rotated.append((int(round(center + rx)), int(round(center + ry))))
    return rotated


def _build_rotation_states():
    states = {}
    for kind, definition in PIECE_DEFS.items():
        size = definition["size"]
        coords = definition["blocks"]
        # Convert to tuples for faster hashing and immutability
        rotations = [tuple(coords)]
        curr = coords
        for _ in range(3):
            curr = _rotate_coords(curr, size, 1)
            rotations.append(tuple(curr))
        states[kind] = rotations
    return states

PIECE_ROTATIONS = _build_rotation_states()

# Precompute rotation states as numpy arrays for faster block calculations
PIECE_ROTATIONS_NP = {}
for kind, rotations in PIECE_ROTATIONS.items():
    PIECE_ROTATIONS_NP[kind] = [np.array(rot, dtype=np.int16) for rot in rotations]

PIECE_ROTATIONS_NP_STACKED = {
    kind: np.stack(rotations, axis=0) for kind, rotations in PIECE_ROTATIONS_NP.items()
}

@njit(cache=True)
def _check_collision_raw(board, shape_offsets, px, py):
    """
    Checks collision without creating new arrays.
    shape_offsets: The precomputed (0,0) based offsets for the piece's rotation.
    px, py: The top-left position of the piece.
    """
    for i in range(len(shape_offsets)):
        # Calculate global position
        nx = shape_offsets[i, 0] + px
        ny = shape_offsets[i, 1] + py

        # Bounds check
        if nx < 0 or nx >= BOARD_WIDTH or ny < 0 or ny >= BOARD_HEIGHT:
            return True # Collision/OOB

        # Board check
        if board[ny, nx] != 0:
            return True # Collision

    return False


@njit(cache=True)
def _bfs_core(
    board,
    shapes,
    kick_table,
    kicks_180_ns,
    kicks_180_ew,
    include_180,
    start_x,
    start_y,
    start_rot,
    last_was_rot,
    last_rot_dir,
    last_kick_index,
    piece_is_o,
):
    height = board.shape[0]
    width = board.shape[1]
    max_states = height * width * 4

    visited = np.zeros((height, width, 4), dtype=np.uint8)
    qx = np.empty(max_states, dtype=np.int16)
    qy = np.empty(max_states, dtype=np.int16)
    qr = np.empty(max_states, dtype=np.int8)
    q_last_was = np.empty(max_states, dtype=np.uint8)
    q_last_dir = np.empty(max_states, dtype=np.int8)
    q_last_kick = np.empty(max_states, dtype=np.int8)

    rx = np.empty(max_states, dtype=np.int16)
    ry = np.empty(max_states, dtype=np.int16)
    rr = np.empty(max_states, dtype=np.int8)
    r_last_was = np.empty(max_states, dtype=np.uint8)
    r_last_dir = np.empty(max_states, dtype=np.int8)
    r_last_kick = np.empty(max_states, dtype=np.int8)

    head = 0
    tail = 0

    if start_x < 0 or start_x >= width or start_y < 0 or start_y >= height:
        return 0, rx, ry, rr, r_last_was, r_last_dir, r_last_kick

    visited[start_y, start_x, start_rot] = 1
    qx[tail] = start_x
    qy[tail] = start_y
    qr[tail] = start_rot
    q_last_was[tail] = 1 if last_was_rot else 0
    q_last_dir[tail] = last_rot_dir
    q_last_kick[tail] = last_kick_index
    tail += 1

    result_count = 0

    while head < tail:
        px = qx[head]
        py = qy[head]
        pr = qr[head]
        last_was = q_last_was[head]
        last_dir = q_last_dir[head]
        last_kick = q_last_kick[head]
        head += 1

        current_shape = shapes[pr]

        if _check_collision_raw(board, current_shape, px, py + 1):
            rx[result_count] = px
            ry[result_count] = py
            rr[result_count] = pr
            r_last_was[result_count] = last_was
            r_last_dir[result_count] = last_dir
            r_last_kick[result_count] = last_kick
            result_count += 1

        # Moves: Left, Right, Down
        for dx, dy in ((-1, 0), (1, 0), (0, 1)):
            nx = px + dx
            ny = py + dy
            if _check_collision_raw(board, current_shape, nx, ny):
                continue
            if visited[ny, nx, pr] == 1:
                continue
            visited[ny, nx, pr] = 1
            qx[tail] = nx
            qy[tail] = ny
            qr[tail] = pr
            q_last_was[tail] = 0
            q_last_dir[tail] = 0
            q_last_kick[tail] = -1
            tail += 1

        # Rotations: CCW, CW, 180 (optional)
        for rot_dir in (-1, 1):
            new_r = (pr + rot_dir) & 3
            new_shape = shapes[new_r]

            success = False
            final_nx = px
            final_ny = py
            final_kick_idx = 0

            if piece_is_o == 1:
                if not _check_collision_raw(board, new_shape, px, py):
                    success = True
            else:
                for k_idx in range(5):
                    ox = kick_table[pr, k_idx, 0]
                    oy = kick_table[pr, k_idx, 1]
                    nx_off = kick_table[new_r, k_idx, 0]
                    ny_off = kick_table[new_r, k_idx, 1]
                    kx = ox - nx_off
                    ky = oy - ny_off
                    tx = px + kx
                    ty = py - ky
                    if not _check_collision_raw(board, new_shape, tx, ty):
                        final_nx = tx
                        final_ny = ty
                        final_kick_idx = k_idx
                        success = True
                        break

            if success and visited[final_ny, final_nx, new_r] == 0:
                visited[final_ny, final_nx, new_r] = 1
                qx[tail] = final_nx
                qy[tail] = final_ny
                qr[tail] = new_r
                q_last_was[tail] = 1
                q_last_dir[tail] = rot_dir
                q_last_kick[tail] = final_kick_idx
                tail += 1

        if include_180:
            rot_dir = 2
            new_r = (pr + rot_dir) & 3
            new_shape = shapes[new_r]

            kicks = kicks_180_ns if (pr & 1) == 0 else kicks_180_ew
            success = False
            final_nx = px
            final_ny = py
            final_kick_idx = 0

            for k_idx in range(kicks.shape[0]):
                kx = kicks[k_idx, 0]
                ky = kicks[k_idx, 1]
                tx = px + kx
                ty = py - ky
                if not _check_collision_raw(board, new_shape, tx, ty):
                    final_nx = tx
                    final_ny = ty
                    final_kick_idx = k_idx
                    success = True
                    break

            if success and visited[final_ny, final_nx, new_r] == 0:
                visited[final_ny, final_nx, new_r] = 1
                qx[tail] = final_nx
                qy[tail] = final_ny
                qr[tail] = new_r
                q_last_was[tail] = 1
                q_last_dir[tail] = rot_dir
                q_last_kick[tail] = final_kick_idx
                tail += 1

    return result_count, rx, ry, rr, r_last_was, r_last_dir, r_last_kick
@njit(cache=True)
def _is_valid_fast(blocks, board):
    for i in range(len(blocks)):
        x, y = blocks[i, 0], blocks[i, 1]
        # Check bounds
        if x < 0 or x >= BOARD_WIDTH or y < 0 or y >= BOARD_HEIGHT:
            return False
        # Check collision
        if board[y, x] != 0:
            return False
    return True


@njit(cache=True)
def _compute_blocks_fast(piece_blocks, ox, oy):
    """Numba-compiled block position calculation."""
    result = np.empty((len(piece_blocks), 2), dtype=np.int16)
    for i in range(len(piece_blocks)):
        result[i, 0] = piece_blocks[i, 0] + ox
        result[i, 1] = piece_blocks[i, 1] + oy
    return result


def _freeze_stats_value(value):
    if isinstance(value, dict):
        return tuple((k, _freeze_stats_value(value[k])) for k in sorted(value))
    if isinstance(value, (list, tuple)):
        return tuple(_freeze_stats_value(v) for v in value)
    if isinstance(value, np.ndarray):
        return tuple(_freeze_stats_value(v) for v in value.tolist())
    if isinstance(value, np.generic):
        return value.item()
    return value


def _dedupe_bfs_results(results):
    unique = []
    seen = {}
    for result in results:
        board = result.get("board")
        stats = result.get("stats")
        placement = result.get("placement")
        if board is None:
            unique.append(result)
            continue
        stats_key = _freeze_stats_value(stats)
        key = (board.shape, board.dtype.str, board.tobytes(), stats_key)
        existing = seen.get(key)
        if existing is None:
            if placement is not None:
                result["placements"] = [placement]
            else:
                result["placements"] = []
            seen[key] = result
            unique.append(result)
        else:
            if placement is not None:
                existing.setdefault("placements", []).append(placement)
    return unique


class Piece:
    def __init__(self, kind, rotation=0, position=(0, 0)):
        if isinstance(kind, int):
            kind = PIECE_ID_TO_KIND.get(kind, kind)
        self.kind = kind
        self.rotation = rotation % 4
        self.position = position

        self.last_action_was_rotation = False
        self.last_rotation_dir: Optional[int] = None
        self.last_kick_index: Optional[int] = None

    def __str__(self):
        return f"{self.kind} at {self.position} (Rot {self.rotation})"

    def copy(self):
        clone = Piece(self.kind, rotation=self.rotation, position=tuple(self.position))
        clone.last_action_was_rotation = bool(self.last_action_was_rotation)
        clone.last_rotation_dir = self.last_rotation_dir
        clone.last_kick_index = self.last_kick_index
        return clone


class TetrisEngine:
    def __init__(self, spin_mode: str = "t_only", rng=None):
        if spin_mode not in {"t_only", "all_spin"}:
            raise ValueError(f"Unsupported spin mode: {spin_mode}")
        self.spin_mode = spin_mode
        self.rng = rng
        self.board = np.zeros((BOARD_HEIGHT, BOARD_WIDTH), dtype=int)
        self.current_piece = None
        self.bag = np.array([], dtype=int)
        self.hold = None
        self.bag_size = 0
        self.b2b_chain = 0
        self.surge_charge = 0
        self.last_clear_stats = None
        self.combo = 0
        self.combo_active = False
        self.game_over = False
        self.game_over_reason = None
        self.last_spawn_was_clutch = False
        self.last_end_phase = None
        # Incoming garbage queue: list of {"lines": int, "timer": int, "col": int}
        self.incoming_garbage: list = []
        # Last garbage hole column (used for change-on-attack randomisation)
        self.garbage_col: Optional[int] = None
        self.generate_bag() # Ensure bag is ready on init

    def reset(self):
        self.board.fill(0)
        self.current_piece = None
        self.hold = None
        self.bag = np.array([], dtype=int)
        self.bag_size = 0
        self.b2b_chain = 0
        self.surge_charge = 0
        self.last_clear_stats = None
        self.combo = 0
        self.combo_active = False
        self.game_over = False
        self.game_over_reason = None
        self.last_spawn_was_clutch = False
        self.last_end_phase = None
        self.incoming_garbage = []
        self.garbage_col = None
        self.generate_bag()

    def _clone_rng(self):
        rng = self.rng
        if rng is None or rng is np.random:
            return rng
        bit_generator = getattr(rng, "bit_generator", None)
        if bit_generator is None:
            return rng
        clone_bit_generator = bit_generator.__class__()
        clone_bit_generator.state = bit_generator.state
        return np.random.Generator(clone_bit_generator)

    def clone(self):
        clone = self.__class__.__new__(self.__class__)
        clone.spin_mode = self.spin_mode
        clone.rng = self._clone_rng()
        clone.board = self.board.copy()
        clone.current_piece = None if self.current_piece is None else self.current_piece.copy()
        clone.bag = self.bag.copy()
        clone.hold = self.hold
        clone.bag_size = int(self.bag_size)
        clone.b2b_chain = int(self.b2b_chain)
        clone.surge_charge = int(self.surge_charge)
        clone.last_clear_stats = None if self.last_clear_stats is None else dict(self.last_clear_stats)
        clone.combo = int(self.combo)
        clone.combo_active = bool(self.combo_active)
        clone.game_over = bool(self.game_over)
        clone.game_over_reason = self.game_over_reason
        clone.last_spawn_was_clutch = bool(self.last_spawn_was_clutch)
        clone.last_end_phase = None if self.last_end_phase is None else dict(self.last_end_phase)
        clone.incoming_garbage = [dict(batch) for batch in self.incoming_garbage]
        clone.garbage_col = self.garbage_col
        return clone

    def __deepcopy__(self, memo):
        clone = self.clone()
        memo[id(self)] = clone
        return clone

    def generate_bag(self):
        # Standard 7-bag randomizer
        if self.bag is None:
            self.bag = np.array([], dtype=int)

        # Ensure we have enough pieces
        while len(self.bag) <= 14:
            rng = self.rng if self.rng is not None else np.random
            new_bag = rng.permutation(7) + 1
            if len(self.bag) == 0:
                self.bag = new_bag
            else:
                self.bag = np.concatenate((self.bag, new_bag))
        self.bag_size = len(self.bag)
        return self.bag

    def print_piece_info(self):
        # Console debug print
        for row in self.board:
            print(" ".join(str(x) for x in row))
        print(f"Current Piece: {self.current_piece}")
        print(f"Hold: {self.hold}")
        print(f"Next: {[PIECE_ID_TO_KIND.get(x,x) for x in self.bag[:5]]}")

    def _spawn_position_for(self, _kind=None):
        return (SPAWN_X, SPAWN_Y)

    def _pop_next_piece_id(self):
        self.generate_bag()
        piece_id = int(self.bag[0])
        self.bag = self.bag[1:]
        self.bag_size = len(self.bag)
        if self.bag_size <= 14:
            self.generate_bag()
        return piece_id

    def spawn_piece(self, kind, position=None, rotation=0):
        if position is None:
            position = self._spawn_position_for(kind)
        piece = Piece(kind, rotation=rotation, position=position)
        self.current_piece = piece
        return piece

    def _find_clutch_spawn(self, piece, position):
        x, y = position
        for ny in range(y - 1, -1, -1):
            if self.is_position_valid(piece, (x, ny)):
                return (x, ny)
        return None

    def spawn_next(self, allow_clutch=False):
        if self.game_over:
            return False

        piece_id = self._pop_next_piece_id()
        spawn_pos = self._spawn_position_for(piece_id)
        piece = Piece(piece_id, rotation=0, position=spawn_pos)

        self.last_spawn_was_clutch = False

        if self.is_position_valid(piece, spawn_pos, rotation=0):
            self.current_piece = piece
            return True

        if allow_clutch:
            clutch_pos = self._find_clutch_spawn(piece, spawn_pos)
            if clutch_pos is not None:
                piece.position = clutch_pos
                self.current_piece = piece
                self.last_spawn_was_clutch = True
                return True

        self.current_piece = None
        self.game_over = True
        self.game_over_reason = "block_out"
        return False

    def _shape_for(self, piece, rotation=None):
        if rotation is None: rotation = piece.rotation
        return PIECE_ROTATIONS[piece.kind][rotation]

    def piece_blocks(self, piece, position=None, rotation=None):
        """Returns global coordinates of the piece's blocks."""
        if position is None: position = piece.position
        if rotation is None: rotation = piece.rotation

        # Use Numba-compiled fast path when available
        blocks_np = PIECE_ROTATIONS_NP[piece.kind][rotation]
        ox, oy = position
        if NUMBA_AVAILABLE:
            return _compute_blocks_fast(blocks_np, ox, oy)
        return blocks_np + np.array([ox, oy], dtype=np.int16)

    def _cell_blocked(self, x, y):
        """Checks bounds and collision."""
        if x < 0 or x >= BOARD_WIDTH or y < 0 or y >= BOARD_HEIGHT:
            return True
        return self.board[y][x] != 0

    def is_position_valid(self, piece, position=None, rotation=None):
        blocks = self.piece_blocks(piece, position, rotation)
        # Use Numba-compiled fast path when available
        if NUMBA_AVAILABLE:
            return _is_valid_fast(blocks, self.board)
        # Fallback: vectorized numpy operations
        if np.any(blocks[:, 0] < 0) or np.any(blocks[:, 0] >= BOARD_WIDTH):
            return False
        if np.any(blocks[:, 1] < 0) or np.any(blocks[:, 1] >= BOARD_HEIGHT):
            return False
        # Check collisions using fancy indexing (much faster)
        return not np.any(self.board[blocks[:, 1], blocks[:, 0]] != 0)

    def _kick_table_for(self, piece):
        if piece.kind == "I": return I_OFFSETS
        if piece.kind == "O": return O_OFFSETS
        return JLSTZ_OFFSETS

    def rotate_piece(self, piece, direction):
        """
        Rotates the piece.
        direction: "CW" (1), "CCW" (-1), "180" (2)
        """
        if direction in ("CW", "cw", 1): delta = 1
        elif direction in ("CCW", "ccw", -1): delta = -1
        elif direction in ("180", 2, -2): delta = 2
        else: return False

        old_state = piece.rotation
        new_state = (old_state + delta) % 4

        # Reset metadata
        piece.last_action_was_rotation = False

        # Helper: Try to apply a kick vector
        def try_kick(kick_x, kick_y, kick_idx):
            # Coordinate Conversion:
            # Kick Y is defined as UP (Standard Cartesian).
            # Board Y is defined as DOWN.
            # Therefore, a Positive Kick Y (Up) means Subtracting from Board Y.

            cx = piece.position[0] + kick_x
            cy = piece.position[1] - kick_y

            if self.is_position_valid(piece, (cx, cy), new_state):
                piece.position = (cx, cy)
                piece.rotation = new_state
                piece.last_action_was_rotation = True
                piece.last_rotation_dir = delta
                piece.last_kick_index = kick_idx
                return True
            return False

        if abs(delta) == 2:
            kicks = KICKS_180_NS if old_state % 2 == 0 else KICKS_180_EW
            for k, (kx, ky) in enumerate(kicks):
                if try_kick(kx, ky, k): return True
            return False

        offsets = self._kick_table_for(piece)

        if piece.kind == "O":
            piece.rotation = new_state
            return True

        for k in range(5):
            ox, oy = offsets[old_state][k]
            nx, ny = offsets[new_state][k]

            kx = ox - nx
            ky = oy - ny

            if try_kick(kx, ky, k): return True

        return False

    def rotate_current(self, direction):
        if self.current_piece is None: return False
        return self.rotate_piece(self.current_piece, direction)

    def _b2b_bonus_for_chain(self, chain_len):
        # The dataset's attack values line up when B2B bonus is applied
        # to the displayed chain (chain_len - 1), not the raw chain_len.
        effective = max(0, chain_len - 1)
        if effective <= 1:
            return 0
        if effective <= 2:
            return 1
        if effective <= 7:
            return 2
        if effective <= 23:
            return 3
        if effective <= 66:
            return 4
        if effective <= 184:
            return 5
        if effective <= 503:
            return 6
        if effective <= 1369:
            return 7
        return 8

    def _is_difficult_clear(self, cleared_lines, spin_result):
        if cleared_lines <= 0:
            return False
        if cleared_lines == 4:
            return True
        # All-Mini+ ruleset: any spin (including mini) is difficult and
        # continues / increments the B2B chain. Singles/Doubles/Triples
        # without a spin are NOT difficult and break the chain.
        if spin_result is not None:
            return True
        return False

    def _update_b2b_and_surge(self, cleared_lines, difficult, b2b_chain, surge_charge):
        """Returns (b2b_chain, surge_charge, b2b_bonus, surge_send).

        Rules (All-Mini+ Tetra League, Feb 2026):
        - Difficult clear (Quad / any Spin incl. Mini): increments b2b_chain,
          computes the log-ladder b2b_bonus, and updates surge_charge.
        - Non-difficult clear (Single/Double/Triple without spin): BREAKS the
          chain — stored surge fires immediately, then both counters reset to 0.
        - No clear (cleared_lines == 0): everything stays unchanged.

        surge_charge tracks total stored lines.  Per mechanics.md:
          "8 B2B streak → 8 lines charged" and "Starts at 4 lines (at streak 4)".
          Therefore surge_charge = b2b_display (= b2b_chain - 1) once that
          display value >= 4, else 0.
        """
        b2b_bonus = 0
        surge_send = 0

        if cleared_lines <= 0:
            return b2b_chain, surge_charge, b2b_bonus, surge_send

        if difficult:
            b2b_chain += 1
            b2b_bonus = self._b2b_bonus_for_chain(b2b_chain)
            b2b_display = b2b_chain - 1
            # Surge starts charging once b2b_display reaches 4, and equals
            # the display value from that point onward.
            surge_charge = b2b_display if b2b_display >= 4 else 0
        else:
            # Chain breaks: release all stored surge lines on this clear.
            surge_send = surge_charge
            b2b_chain = 0
            surge_charge = 0

        return b2b_chain, surge_charge, b2b_bonus, surge_send

    def _surge_segments(self, total):
        if total <= 0:
            return []
        base = total // 3
        rem = total % 3
        seg1 = base + (1 if rem > 0 else 0)
        seg2 = base + (1 if rem > 1 else 0)
        seg3 = base
        return [seg1, seg2, seg3]

    def _base_attack_for_clear(self, cleared_lines, spin_result, board_after_clear):
        if cleared_lines <= 0:
            return 0, False

        perfect_clear = bool(np.all(board_after_clear == 0))
        if perfect_clear:
            return 10, True

        if spin_result is not None and spin_result.get("spin_type") == "t-spin":
            is_mini = bool(spin_result.get("is_mini"))
            if is_mini:
                if cleared_lines == 1:
                    return 0, False
                if cleared_lines == 2:
                    return 1, False
            else:
                if cleared_lines == 1:
                    return 2, False
                if cleared_lines == 2:
                    return 4, False
                if cleared_lines == 3:
                    return 6, False

        if cleared_lines == 1:
            return 0, False
        if cleared_lines == 2:
            return 1, False
        if cleared_lines == 3:
            return 2, False
        if cleared_lines == 4:
            return 4, False

        return 0, False

    def _update_combo(self, cleared_lines):
        self.combo, self.combo_active = self._combo_after_clear(
            cleared_lines, self.combo, self.combo_active
        )
        return self.combo

    def _combo_after_clear(self, cleared_lines, combo, combo_active):
        if cleared_lines <= 0:
            return 0, False
        if combo_active:
            return combo + 1, True
        return 0, True

    def combo_attack_down(self, base_attack, combo=None):
        if combo is None:
            combo = self.combo
        if base_attack > 0:
            value = base_attack * (1.0 + 0.25 * combo)
        else:
            if combo >= 2:
                value = math.log(1.0 + 1.25 * combo)
            else:
                value = 0.0
        return int(math.floor(value))

    def _clear_lines_on_board(self, board):
        full_rows = np.where(np.all(board != 0, axis=1))[0]
        if full_rows.size == 0:
            return board, 0
        new_board = np.delete(board, full_rows, axis=0)
        new_rows = np.zeros((len(full_rows), BOARD_WIDTH), dtype=board.dtype)
        new_board = np.vstack((new_rows, new_board))
        return new_board, int(full_rows.size)

    def _simulate_lock(self, piece, b2b_chain=None, combo=None, combo_active=None, base_attack=None, surge_charge=None):
        if b2b_chain is None:
            b2b_chain = self.b2b_chain
        if combo is None:
            combo = self.combo
        if combo_active is None:
            combo_active = self.combo_active
        if surge_charge is None:
            surge_charge = self.surge_charge

        spin_result = self.detect_spin(piece)

        if isinstance(piece.kind, int):
            piece_id = piece.kind
        else:
            piece_id = KIND_TO_PIECE_ID.get(piece.kind, 1)

        board = self.board.copy()
        blocks = self.piece_blocks(piece)
        valid_mask = (blocks[:, 0] >= 0) & (blocks[:, 0] < BOARD_WIDTH) & \
                     (blocks[:, 1] >= 0) & (blocks[:, 1] < BOARD_HEIGHT)
        valid_blocks = blocks[valid_mask]
        if len(valid_blocks) > 0:
            board[valid_blocks[:, 1], valid_blocks[:, 0]] = piece_id

        board, cleared = self._clear_lines_on_board(board)
        computed_base_attack, perfect_clear = self._base_attack_for_clear(
            cleared, spin_result, board
        )
        if base_attack is None:
            base_attack = computed_base_attack

        combo, combo_active = self._combo_after_clear(cleared, combo, combo_active)
        difficult = self._is_difficult_clear(cleared, spin_result)
        b2b_chain, surge_charge, b2b_bonus, surge_send = self._update_b2b_and_surge(
            cleared, difficult, b2b_chain, surge_charge
        )

        combo_attack = None
        combo_bonus = None
        combo_multiplier = None
        if base_attack is not None:
            combo_attack = self.combo_attack_down(base_attack, combo=combo)
            combo_bonus = combo_attack - base_attack
            combo_multiplier = 1.0 + 0.25 * combo if base_attack > 0 else None
        attack_total = None
        if combo_attack is not None:
            attack_total = combo_attack + b2b_bonus + surge_send

        t_spin_flag = "N"
        if spin_result is not None:
            t_spin_flag = "M" if spin_result.get("is_mini") else "F"

        stats = {
            "lines_cleared": cleared,
            "spin": spin_result,
            "t_spin": t_spin_flag,
            "perfect_clear": perfect_clear,
            "is_difficult": difficult,
            "b2b_chain": b2b_chain,
            "b2b_display": max(0, b2b_chain - 1) if difficult else 0,
            "b2b_bonus": b2b_bonus,
            "surge_charge": surge_charge,
            "surge_send": surge_send,
            "surge_segments": self._surge_segments(surge_send),
            "combo": combo,
            "combo_attack": combo_attack,
            "combo_bonus": combo_bonus,
            "combo_multiplier": combo_multiplier,
            "base_attack": base_attack,
            "attack": attack_total,
            "garbage_cleared": 0,
            "immediate_garbage": 0,
        }

        return board, stats

    def bfs_all_placements(
        self,
        piece=None,
        include_180=True,
        base_attack=None,
        include_no_place=True,
        dedupe_final=True,
    ):
        if piece is None:
            piece = self.current_piece
        if piece is None:
            if include_no_place:
                return [{
                    "board": self.board.copy(),
                    "stats": None,
                    "placement": {"skip": True},
                }]
            return []

        # Extract primitive data
        kind = piece.kind
        start_x, start_y = piece.position
        start_rot = piece.rotation

        # Pre-fetch kick tables and shapes for speed
        if kind == "I":
            kick_table = I_OFFSETS
            kick_table_arr = I_OFFSETS_ARR
        elif kind == "O":
            kick_table = O_OFFSETS
            kick_table_arr = O_OFFSETS_ARR
        else:
            kick_table = JLSTZ_OFFSETS
            kick_table_arr = JLSTZ_OFFSETS_ARR

        shapes = PIECE_ROTATIONS_NP[kind] # List of 4 arrays
        shapes_arr = PIECE_ROTATIONS_NP_STACKED[kind]

        results = []
        if include_no_place:
            results.append({
                "board": self.board.copy(),
                "stats": None,
                "placement": {"skip": True},
            })

        if NUMBA_AVAILABLE:
            piece_is_o = 1 if kind == "O" else 0
            last_rot_dir = 0 if piece.last_rotation_dir is None else int(piece.last_rotation_dir)
            last_kick_idx = -1 if piece.last_kick_index is None else int(piece.last_kick_index)
            count, rx, ry, rr, r_last_was, r_last_dir, r_last_kick = _bfs_core(
                self.board,
                shapes_arr,
                kick_table_arr,
                KICKS_180_NS_ARR,
                KICKS_180_EW_ARR,
                include_180,
                start_x,
                start_y,
                start_rot,
                piece.last_action_was_rotation,
                last_rot_dir,
                last_kick_idx,
                piece_is_o,
            )
            for i in range(count):
                px = int(rx[i])
                py = int(ry[i])
                pr = int(rr[i])
                last_was_rot = bool(r_last_was[i])
                last_dir = int(r_last_dir[i])
                last_kick = int(r_last_kick[i])

                p_obj = Piece(kind, rotation=pr, position=(px, py))
                p_obj.last_action_was_rotation = last_was_rot
                p_obj.last_rotation_dir = None if last_dir == 0 else last_dir
                p_obj.last_kick_index = None if last_kick < 0 else last_kick

                final_board, stats = self._simulate_lock(p_obj, base_attack=base_attack)
                results.append({
                    "board": final_board,
                    "stats": stats,
                    "placement": {
                        "x": px, "y": py,
                        "r": ["N", "E", "S", "W"][pr],
                        "rotation": pr,
                        "kind": kind,
                        "last_was_rot": last_was_rot,
                        "last_rot_dir": None if last_dir == 0 else last_dir,
                        "last_kick_idx": None if last_kick < 0 else last_kick,
                    },
                })

            return _dedupe_bfs_results(results) if dedupe_final else results

        # Queue: (x, y, rot, last_was_rot, last_rot_dir, last_kick_idx)
        start_node = (start_x, start_y, start_rot, piece.last_action_was_rotation, piece.last_rotation_dir, piece.last_kick_index)

        queue = deque([start_node])
        visited = np.zeros((BOARD_HEIGHT, BOARD_WIDTH, 4), dtype=np.bool_)
        visited[start_y, start_x, start_rot] = True


        rotation_actions = [1, -1, 2] if include_180 else [1, -1]

        # Numba optimization accessor
        board = self.board

        while queue:
            # Unpack tuple (Fast!)
            px, py, pr, last_was_rot, last_rot_dir, last_kick = queue.popleft()

            # 1. LOCK CHECK (Can we move down?)
            # Check collision at (px, py + 1) using raw Numba check
            # We use the shape for the CURRENT rotation `pr`
            current_shape = shapes[pr]

            can_move_down = not _check_collision_raw(board, current_shape, px, py + 1)

            if not can_move_down:
                # Reconstruct Piece object ONLY for result generation
                p_obj = Piece(kind, rotation=pr, position=(px, py))
                p_obj.last_action_was_rotation = last_was_rot
                p_obj.last_rotation_dir = last_rot_dir
                p_obj.last_kick_index = last_kick

                final_board, stats = self._simulate_lock(p_obj, base_attack=base_attack)
                results.append({
                    "board": final_board,
                    "stats": stats,
                    "placement": {
                        "x": px, "y": py,
                        "r": ["N", "E", "S", "W"][pr],
                        "rotation": pr,
                        "kind": kind,
                        "last_was_rot": last_was_rot,
                        "last_rot_dir": last_rot_dir,
                        "last_kick_idx": last_kick,
                    },
                })

            # 2. MOVES (Left, Right, Down)
            # Translations reset rotation flags
            for dx, dy in [(-1, 0), (1, 0), (0, 1)]:
                nx, ny = px + dx, py + dy

                # Check collision directly (also rejects OOB)
                if _check_collision_raw(board, current_shape, nx, ny):
                    continue
                if visited[ny, nx, pr]:
                    continue

                visited[ny, nx, pr] = True
                queue.append((nx, ny, pr, False, None, None))

            # 3. ROTATIONS
            for rot_dir in rotation_actions:
                new_r = (pr + rot_dir) % 4
                new_shape = shapes[new_r]

                # Perform Kick Logic (Integer Arithmetic)
                success = False
                final_nx, final_ny, final_kick_idx = px, py, 0

                # 180 Kicks
                if abs(rot_dir) == 2:
                    kicks = KICKS_180_NS if pr % 2 == 0 else KICKS_180_EW
                    for k_idx, (kx, ky) in enumerate(kicks):
                        # Apply Kick (Y is up in kick table, down in board)
                        tx, ty = px + kx, py - ky
                        if not _check_collision_raw(board, new_shape, tx, ty):
                            final_nx, final_ny, final_kick_idx = tx, ty, k_idx
                            success = True
                            break
                # Standard Kicks
                else:
                    if kind == "O":
                        # O-piece rotates in place (effectively)
                        if not _check_collision_raw(board, new_shape, px, py):
                            success = True
                            final_nx, final_ny, final_kick_idx = px, py, 0
                    else:
                        # SRS Kicks
                        for k_idx in range(5):
                            ox, oy = kick_table[pr][k_idx]
                            nx_off, ny_off = kick_table[new_r][k_idx]
                            kx = ox - nx_off
                            ky = oy - ny_off

                            tx, ty = px + kx, py - ky
                            if not _check_collision_raw(board, new_shape, tx, ty):
                                final_nx, final_ny, final_kick_idx = tx, ty, k_idx
                                success = True
                                break

                if success:
                    if not visited[final_ny, final_nx, new_r]:
                        visited[final_ny, final_nx, new_r] = True
                        queue.append((final_nx, final_ny, new_r, True, rot_dir, final_kick_idx))

        return _dedupe_bfs_results(results) if dedupe_final else results

    def lock_piece(self, piece=None, run_end_phase=False, base_attack=None):
        if piece is None:
            piece = self.current_piece
        if piece is None:
            return 0
        spin_result = self.detect_spin(piece)
        if isinstance(piece.kind, int):
            piece_id = piece.kind
        else:
            piece_id = KIND_TO_PIECE_ID.get(piece.kind, 1)

        blocks = self.piece_blocks(piece)
        valid_mask = (blocks[:, 0] >= 0) & (blocks[:, 0] < BOARD_WIDTH) & \
                     (blocks[:, 1] >= 0) & (blocks[:, 1] < BOARD_HEIGHT)
        valid_blocks = blocks[valid_mask]
        if len(valid_blocks) > 0:
            self.board[valid_blocks[:, 1], valid_blocks[:, 0]] = piece_id
        self.current_piece = None
        locked_in_hidden = bool(np.all(blocks[:, 1] < HIDDEN_ROWS))
        cleared = self.clear_lines()
        computed_base_attack, perfect_clear = self._base_attack_for_clear(
            cleared, spin_result, self.board
        )
        if base_attack is None:
            base_attack = computed_base_attack
        combo = self._update_combo(cleared)
        difficult = self._is_difficult_clear(cleared, spin_result)
        self.b2b_chain, self.surge_charge, b2b_bonus, surge_send = self._update_b2b_and_surge(
            cleared, difficult, self.b2b_chain, self.surge_charge
        )
        combo_attack = None
        combo_bonus = None
        combo_multiplier = None
        if base_attack is not None:
            combo_attack = self.combo_attack_down(base_attack, combo=combo)
            combo_bonus = combo_attack - base_attack
            combo_multiplier = 1.0 + 0.25 * combo if base_attack > 0 else None
        attack_total = None
        if combo_attack is not None:
            attack_total = combo_attack + b2b_bonus + surge_send

        self.last_clear_stats = {
            "lines_cleared": cleared,
            "spin": spin_result,
            "is_difficult": difficult,
            "b2b_chain": self.b2b_chain,
            "b2b_display": max(0, self.b2b_chain - 1) if difficult else 0,
            "b2b_bonus": b2b_bonus,
            "surge_charge": self.surge_charge,
            "surge_send": surge_send,
            "surge_segments": self._surge_segments(surge_send),
            "combo": combo,
            "combo_attack": combo_attack,
            "combo_bonus": combo_bonus,
            "combo_multiplier": combo_multiplier,
            "base_attack": base_attack,
            "perfect_clear": perfect_clear,
            "attack": attack_total,
        }
        if not self.game_over and locked_in_hidden and cleared == 0:
            self.game_over = True
            self.game_over_reason = "lock_out"
        if run_end_phase:
            self.last_end_phase = self.end_phase(cleared)
        return cleared

    def lock_and_spawn(self, piece=None):
        cleared = self.lock_piece(piece=piece, run_end_phase=False)
        self.last_end_phase = self.end_phase(cleared)
        return cleared, self.last_end_phase

    def end_phase(self, cleared_lines):
        result = {
            "lines_cleared": cleared_lines,
            "spawned": False,
            "clutch_clear": False,
            "game_over": self.game_over,
            "reason": self.game_over_reason,
        }

        if self.game_over:
            return result

        spawned = self.spawn_next(allow_clutch=cleared_lines > 0)
        result["spawned"] = spawned
        result["clutch_clear"] = self.last_spawn_was_clutch
        result["game_over"] = self.game_over
        result["reason"] = self.game_over_reason
        return result

    def clear_lines(self):
        full_rows = np.where(np.all(self.board != 0, axis=1))[0]
        if full_rows.size == 0:
            return 0
        self.board = np.delete(self.board, full_rows, axis=0)
        new_rows = np.zeros((len(full_rows), BOARD_WIDTH), dtype=self.board.dtype)
        self.board = np.vstack((new_rows, self.board))
        return int(full_rows.size)

    # ------------------------------------------------------------------ #
    #  Incoming Garbage                                                    #
    # ------------------------------------------------------------------ #

    def add_incoming_garbage(self, lines: int, timer: int = 60, col: Optional[int] = None) -> None:
        """Enqueue an incoming garbage batch.

        Parameters
        ----------
        lines : Number of garbage lines in this batch.
        timer : Ticks until the garbage lands (default 60 ≈ 1 second at 60 fps).
        col   : Hole column (0-9).  If None, picks a random column that is
                different from the previous batch's column (TETR.IO
                change-on-attack rule).
        """
        if lines <= 0:
            return
        if col is None:
            prev_col = self.incoming_garbage[-1]["col"] if self.incoming_garbage else self.garbage_col
            available = [c for c in range(BOARD_WIDTH) if c != prev_col]
            rng = self.rng if self.rng is not None else np.random
            col = int(rng.choice(available))
        self.incoming_garbage.append({"lines": int(lines), "timer": int(timer), "col": int(col)})

    def cancel_garbage(self, attack: int) -> int:
        """Cancel pending incoming garbage using outgoing attack lines.

        Cancels from the oldest pending batch first.  Returns any leftover
        attack that exceeded the total pending garbage.
        """
        remaining = int(attack)
        while remaining > 0 and self.incoming_garbage:
            batch = self.incoming_garbage[0]
            if batch["lines"] <= remaining:
                remaining -= batch["lines"]
                self.incoming_garbage.pop(0)
            else:
                batch["lines"] -= remaining
                remaining = 0
        return remaining

    def apply_garbage(self, lines: int, col: int) -> None:
        """Push ``lines`` garbage rows onto the bottom of the board.

        Each garbage row is fully filled except for a single hole at column
        ``col``.  Rows above are shifted up; any rows that scroll past the top
        of the board are lost (top-out is checked separately in lock_piece).
        """
        if lines <= 0:
            return
        garbage_row = np.full(BOARD_WIDTH, -1, dtype=self.board.dtype)  # -1 = garbage
        garbage_row[col] = 0  # hole
        new_rows = np.tile(garbage_row, (lines, 1))
        # Shift the board up and append the new garbage rows at the bottom.
        self.board = np.vstack((self.board[lines:], new_rows))
        self.garbage_col = col

    def tick_garbage(self) -> int:
        """Advance all garbage timers by one tick and apply any that expire.

        Returns the total number of garbage lines that actually landed this
        tick so callers can check for a resulting top-out.
        """
        landed = 0
        still_pending = []
        for batch in self.incoming_garbage:
            batch["timer"] -= 1
            if batch["timer"] <= 0:
                self.apply_garbage(batch["lines"], batch["col"])
                landed += batch["lines"]
            else:
                still_pending.append(batch)
        self.incoming_garbage = still_pending
        return landed

    def detect_spin(self, piece):
        """
        TETR.IO Spin Detection Algorithm

        Pre-condition: Last action must have been a successful rotation.

        Default mode: T-Spins only, using the 3-corner rule plus face rule.
        Optional mode: non-T all-spins via immobility check.
        """
        if not piece.last_action_was_rotation:
            return None

        if piece.kind == "T":
            return self._detect_t_spin(piece)
        elif self.spin_mode == "all_spin" and piece.kind in ("J", "L", "S", "Z", "I"):
            return self._detect_all_spin(piece)

        return None

    def _detect_t_spin(self, piece):
        corners_occupied = self._occupied_3x3_corners(piece)
        if corners_occupied < 3:
            return None

        rotation_dir = 0 if piece.last_rotation_dir is None else int(piece.last_rotation_dir)
        is_180 = abs(rotation_dir) == 2
        front_corners = self._count_t_front_corners(piece)
        is_full = is_180 or piece.last_kick_index == 4 or front_corners == 2
        is_mini = not is_full

        return {
            "piece": "T",
            "spin_type": "t-spin",
            "is_mini": is_mini,
            "is_180": is_180,
            "corners": corners_occupied,
            "front_corners": front_corners,
            "kick_index": piece.last_kick_index,
            "rotation_dir": rotation_dir,
            "description": f"{'180 ' if is_180 else ''}T-Spin{' Mini' if is_mini else ''}"
        }

    def _detect_all_spin(self, piece):
        """
        All-Spin Detection (J, L, S, Z, I)

        Requirement: Piece must be immobile (cannot move left, right, or up)
        """
        px, py = piece.position

        can_move_left = self.is_position_valid(piece, (px - 1, py))
        can_move_right = self.is_position_valid(piece, (px + 1, py))
        can_move_up = self.is_position_valid(piece, (px, py - 1))

        if can_move_left or can_move_right or can_move_up:
            return None

        return {
            "piece": piece.kind,
            "spin_type": "spin",
            "is_mini": True,
            "is_180": abs(piece.last_rotation_dir) == 2,
            "kick_index": piece.last_kick_index,
            "rotation_dir": piece.last_rotation_dir,
            "description": f"{piece.kind}-Spin Mini"
        }

    def _occupied_3x3_corners(self, piece):
        """Count how many of the 4 corners of a 3x3 bounding box are occupied."""
        px, py = piece.position
        corners = [(0, 0), (2, 0), (0, 2), (2, 2)]
        occupied = 0
        for cx, cy in corners:
            if self._cell_blocked(px + cx, py + cy):
                occupied += 1
        return occupied

    def _count_t_front_corners(self, piece):
        """
        Count occupied front corners based on T-piece rotation.

        Front corners are the two corners the T is "facing":
        - Rotation 0 (pointing up): Top corners (0,0) and (2,0)
        - Rotation 1 (pointing right): Right corners (2,0) and (2,2)
        - Rotation 2 (pointing down): Bottom corners (0,2) and (2,2)
        - Rotation 3 (pointing left): Left corners (0,0) and (0,2)
        """
        px, py = piece.position
        rotation = piece.rotation

        front_corners = {
            0: [(0, 0), (2, 0)],
            1: [(2, 0), (2, 2)],
            2: [(0, 2), (2, 2)],
            3: [(0, 0), (0, 2)],
        }

        corners = front_corners[rotation]
        occupied = 0
        for cx, cy in corners:
            if self._cell_blocked(px + cx, py + cy):
                occupied += 1

        return occupied
